framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus

        buses:
           command.bus: ~
           event.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                 dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                 retry_strategy:
                     delay: 500
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            #'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Messanger\Message\Event\UserRegisteredEvent': async