twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_5_layout.html.twig']              # todo themes for twig form

when@test:
    twig:
        strict_variables: true
